spring:
  datasource:
    # 시스템 속성(로컬) 또는 OS 환경 변수(배포)에서 가져옴
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true # 배포 시 false로 바꿀 것
        format_sql: true # 배포 시 false로 바꿀 것
        use_sql_comments: true # 배포 시 false로 바꿀 것

app:
  url: ${APP_URL:http://localhost:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# --- 외부 API 연동 설정 ---
google:
  places:
    # .env 파일 또는 시스템 환경 변수에 선언된 GOOGLE_MAP_API_KEY 값을 주입받습니다.
    # 추후 Service 클래스에서 @Value("${google.places.api-key}") 형태로 꺼내어 사용합니다.
    api-key: ${GOOGLE_MAP_API_KEY}

openrouteservice:
  base-url: https://api.openrouteservice.org
  api-key: ${ORS_API_KEY}

tago:
  api:
    base-url: https://apis.data.go.kr/1613000/ArvlInfoInqireService
    station-base-url: https://apis.data.go.kr/1613000/BusSttnInfoInqireService
    service-key: ${TAGO_API_KEY}

odsay:
  api:
    base-url: https://api.odsay.com
    api-key: ${ODSAY_API_KEY}